version: '3.1'
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password --init-file /etc/mysql/conf.d/init.sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
    - 3306:3306
    volumes:
    - ./mysqlconf:/etc/mysql/conf.d/


  adminer:
    image: adminer
    restart: always
    ports:
    - 8080:8080


