CREATE TABLE BLOQUED_IP (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  IP VARCHAR(256) NOT NULL,
  COMMENT VARCHAR(256) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE IP_REQUEST (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  DATE DATETIME NOT NULL,
  IP VARCHAR(256) NOT NULL,
  STATUS INT NOT NULL,
  REQUEST VARCHAR(256) NOT NULL,
  USER_AGENT VARCHAR(256) NOT NULL,
  PRIMARY KEY (ID),
  UNIQUE (DATE)
);

SELECT count(*) as request FROM IP_REQUEST WHERE DATE >= '2017-01-01.13:00:00' and DATE <= '2017-01-01.14:00:00' group by IP

SELECT count(*) FROM IP_REQUEST WHERE IP = ?