CREATE DATABASE IF NOT EXISTS PARSER;
use PARSER;
CREATE TABLE IF NOT EXISTS BLOCKED_IP (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  IP VARCHAR(256) NOT NULL,
  COMMENT VARCHAR(256) NOT NULL,
  PRIMARY KEY (ID)
);


CREATE TABLE IF NOT EXISTS IP_REQUEST (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  DATE DATETIME NOT NULL,
  IP VARCHAR(256) NOT NULL,
  STATUS INT NOT NULL,
  REQUEST VARCHAR(256) NOT NULL,
  USER_AGENT VARCHAR(256) NOT NULL,
  PRIMARY KEY (ID),
  UNIQUE (DATE)
);